name: Run Playwright Automated Tests

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Select which browser to test
        required: true
        options:
          - chromium
          - firefox
          - webkit

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test login.spec.ts --project ${{github.event.inputs.browser || 'chromium'}}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30


